server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

    gateway:
      # 网关的核心之一 => route（路由） - 进行路径匹配
      routes:
        - id: pay_routh1 # pay_routh1                # 路由的 ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001                # 匹配后提供服务的路由地址（问题是出现路径写死问题，一般不止一个微服务提供者）
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由（true 可以访问）
            # 下面是通过 predicate 进行 After-Route-Predicate 断言（表示在该时间之后网关才会放行请求）
            - After=2025-01-21T11:06:43.305109100+08:00[Asia/Shanghai] # 请求需要在此之后才能被放行
            - Cookie=username,jieHFUT # 请求中需要携带该 cookie
            - Header=X-Request-Id, \d+ # 请求头需要携带该信息，根据正则表达式进行匹配
            - Host=**.baidu.com,**.jieHFUT.cloud # 根据域名进行匹配
            - Query=colour, green # 请求中携带参数，参数值可以是正则表达式
            - RemoteAddr=192.168.51.39/24 # 外部访问我的IP限制，最大跨度不超过 32，目前是 1~24它们是 CIDR 表示法。
            - Method=GET,POST # 限制请求方法
            # 自定义断言工厂
            - name: My
              args:
                requestRank: gold


        - id: pay_routh2 # pay_routh2                # 路由的 ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001                # 匹配后提供服务的路由地址（问题是出现路径写死问题，一般不止一个微服务提供者）
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**             # 断言，路径相匹配的进行路由（true 可以访问）